#spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: http://localhost:8080/realms/quickstart/protocol/openid-connect/certs

#################################################################################################

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://192.168.1.16:8080/realms/Training/protocol/openid-connect/token